#! /bin/sh

sh $HOME/scripts/launch &

# bspc monitor DP1-1 I II III IV V VI VII VIII
bspc monitor eDP1 -d I II III IV V VI VII VIII
# bspc monitor DP1-2 -d IX X

bspc config border_width         4
bspc config window_gap          30
bspc config top_padding		0
bspc config bottom_padding	 0

bspc config active_border_color "#368DFF"
bspc config focused_border_color "#368DFF"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follow_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Spotify desktop='^7' follow=on
bspc rule -a Plank layer=normal manage=one border=off focus=off locked=off
bspc rule -a terminal-float state=floating
bspc rule -a galandae layer=top manage=off
